"""Add cascades to some tables

Revision ID: 06196fd8dcdc
Revises: 2331d80fb6f9
Create Date: 2025-05-26 21:11:17.773288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06196fd8dcdc'
down_revision: Union[str, None] = '2331d80fb6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('belbin_answers_question_id_fkey', 'belbin_answers', type_='foreignkey')
    op.drop_constraint('belbin_answers_role_id_fkey', 'belbin_answers', type_='foreignkey')
    op.create_foreign_key(None, 'belbin_answers', 'belbin_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'belbin_answers', 'belbin_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('belbin_position_requirements_role_id_fkey', 'belbin_position_requirements', type_='foreignkey')
    op.drop_constraint('belbin_position_requirements_position_id_fkey', 'belbin_position_requirements', type_='foreignkey')
    op.create_foreign_key(None, 'belbin_position_requirements', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'belbin_position_requirements', 'belbin_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('belbin_questions_test_id_fkey', 'belbin_questions', type_='foreignkey')
    op.create_foreign_key(None, 'belbin_questions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('belbin_test_results_test_id_fkey', 'belbin_test_results', type_='foreignkey')
    op.drop_constraint('belbin_test_results_role_id_fkey', 'belbin_test_results', type_='foreignkey')
    op.create_foreign_key(None, 'belbin_test_results', 'test_results', ['test_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'belbin_test_results', 'belbin_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employees_created_by_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employees', ['created_by_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('user_answer_items_user_answer_id_fkey', 'user_answer_items', type_='foreignkey')
    op.drop_constraint('user_answer_items_answer_id_fkey', 'user_answer_items', type_='foreignkey')
    op.create_foreign_key(None, 'user_answer_items', 'user_answers', ['user_answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_answer_items', 'answers', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_answers_test_id_fkey', 'user_answers', type_='foreignkey')
    op.drop_constraint('user_answers_question_id_fkey', 'user_answers', type_='foreignkey')
    op.drop_constraint('user_answers_answer_id_fkey', 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_answers', 'answers', ['answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_answers', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_belbin_answers_test_id_fkey', 'user_belbin_answers', type_='foreignkey')
    op.drop_constraint('user_belbin_answers_answer_id_fkey', 'user_belbin_answers', type_='foreignkey')
    op.drop_constraint('user_belbin_answers_question_id_fkey', 'user_belbin_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_belbin_answers', 'belbin_answers', ['answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_belbin_answers', 'belbin_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_belbin_answers', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_belbin_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_belbin_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_belbin_answers', type_='foreignkey')
    op.create_foreign_key('user_belbin_answers_question_id_fkey', 'user_belbin_answers', 'belbin_questions', ['question_id'], ['id'])
    op.create_foreign_key('user_belbin_answers_answer_id_fkey', 'user_belbin_answers', 'belbin_answers', ['answer_id'], ['id'])
    op.create_foreign_key('user_belbin_answers_test_id_fkey', 'user_belbin_answers', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key('user_answers_answer_id_fkey', 'user_answers', 'answers', ['answer_id'], ['id'])
    op.create_foreign_key('user_answers_question_id_fkey', 'user_answers', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('user_answers_test_id_fkey', 'user_answers', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'user_answer_items', type_='foreignkey')
    op.drop_constraint(None, 'user_answer_items', type_='foreignkey')
    op.create_foreign_key('user_answer_items_answer_id_fkey', 'user_answer_items', 'answers', ['answer_id'], ['id'])
    op.create_foreign_key('user_answer_items_user_answer_id_fkey', 'user_answer_items', 'user_answers', ['user_answer_id'], ['id'])

    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_created_by_id_fkey', 'employees', 'employees', ['created_by_id'], ['id'])
    op.drop_constraint(None, 'belbin_test_results', type_='foreignkey')
    op.drop_constraint(None, 'belbin_test_results', type_='foreignkey')
    op.create_foreign_key('belbin_test_results_role_id_fkey', 'belbin_test_results', 'belbin_roles', ['role_id'], ['id'])
    op.create_foreign_key('belbin_test_results_test_id_fkey', 'belbin_test_results', 'test_results', ['test_id'], ['id'])
    op.drop_constraint(None, 'belbin_questions', type_='foreignkey')
    op.create_foreign_key('belbin_questions_test_id_fkey', 'belbin_questions', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'belbin_position_requirements', type_='foreignkey')
    op.drop_constraint(None, 'belbin_position_requirements', type_='foreignkey')
    op.create_foreign_key('belbin_position_requirements_position_id_fkey', 'belbin_position_requirements', 'positions', ['position_id'], ['id'])
    op.create_foreign_key('belbin_position_requirements_role_id_fkey', 'belbin_position_requirements', 'belbin_roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'belbin_answers', type_='foreignkey')
    op.drop_constraint(None, 'belbin_answers', type_='foreignkey')
    op.create_foreign_key('belbin_answers_role_id_fkey', 'belbin_answers', 'belbin_roles', ['role_id'], ['id'])
    op.create_foreign_key('belbin_answers_question_id_fkey', 'belbin_answers', 'belbin_questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
