"""Delete position column in test

Revision ID: 066b927e02b5
Revises: 3bdacd81ef1d
Create Date: 2025-05-06 21:48:22.912626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066b927e02b5'
down_revision: Union[str, None] = '3bdacd81ef1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tests_position_id_fkey', 'tests', type_='foreignkey')
    op.drop_column('tests', 'position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tests_position_id_fkey', 'tests', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###
