"""Fix belbinTestResult links

Revision ID: 0a4377f670c0
Revises: b83403dac9e3
Create Date: 2025-05-21 21:36:21.743492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4377f670c0'
down_revision: Union[str, None] = 'b83403dac9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('belbin_test_results_test_id_fkey', 'belbin_test_results', type_='foreignkey')
    op.create_foreign_key(None, 'belbin_test_results', 'test_results', ['test_id'], ['id'])
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_constraint(None, 'belbin_test_results', type_='foreignkey')
    op.create_foreign_key('belbin_test_results_test_id_fkey', 'belbin_test_results', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###
