"""Delete table belbinresult

Revision ID: 14f8daaaa2c1
Revises: 0a4377f670c0
Create Date: 2025-05-21 22:26:30.723149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f8daaaa2c1'
down_revision: Union[str, None] = '0a4377f670c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_belbin_results_id', table_name='belbin_results')
    op.drop_table('belbin_results')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('belbin_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_result_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['belbin_roles.id'], name='belbin_results_role_id_fkey'),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], name='belbin_results_test_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='belbin_results_pkey')
    )
    op.create_index('ix_belbin_results_id', 'belbin_results', ['id'], unique=False)
    # ### end Alembic commands ###
