"""Fix belbin question

Revision ID: 2a78eada28fe
Revises: baae11aaae99
Create Date: 2025-05-08 21:48:57.198168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a78eada28fe'
down_revision: Union[str, None] = 'baae11aaae99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('belbin_answers', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('belbin_answers', sa.Column('text', sa.String(), nullable=False))
    op.create_foreign_key(None, 'belbin_answers', 'belbin_roles', ['role_id'], ['id'])
    op.drop_constraint('belbin_questions_role_id_fkey', 'belbin_questions', type_='foreignkey')
    op.drop_column('belbin_questions', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('belbin_questions', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('belbin_questions_role_id_fkey', 'belbin_questions', 'belbin_roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'belbin_answers', type_='foreignkey')
    op.drop_column('belbin_answers', 'text')
    op.drop_column('belbin_answers', 'role_id')
    # ### end Alembic commands ###
