"""Add creat_by for some tables

Revision ID: 30f18779a783
Revises: 51b1fc3d45b1
Create Date: 2025-05-05 23:07:10.824133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f18779a783'
down_revision: Union[str, None] = '51b1fc3d45b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_employees_created_by'), 'employees', ['created_by'], unique=False)
    op.add_column('positions', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_positions_created_by'), 'positions', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_created_by'), table_name='positions')
    op.drop_column('positions', 'created_by')
    op.drop_index(op.f('ix_employees_created_by'), table_name='employees')
    op.drop_column('employees', 'created_by')
    # ### end Alembic commands ###
