"""Add image column to tests

Revision ID: 3bdacd81ef1d
Revises: 5609ab73fbdb
Create Date: 2025-05-06 19:04:17.521015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdacd81ef1d'
down_revision: Union[str, None] = '5609ab73fbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_positions_title'), 'positions', ['title'], unique=False)
    op.add_column('questions', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('tests', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'image')
    op.drop_column('questions', 'image')
    op.drop_index(op.f('ix_positions_title'), table_name='positions')
    op.drop_column('answers', 'image')
    # ### end Alembic commands ###
