"""Add started_at in TestResult

Revision ID: 42f0818c8630
Revises: 768c9d0e815e
Create Date: 2025-05-11 16:25:39.171534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f0818c8630'
down_revision: Union[str, None] = '768c9d0e815e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'started_at')
    # ### end Alembic commands ###
