"""Add answer_id in UserBelbinAnswer table

Revision ID: 4a8c09233930
Revises: 9cd99830e250
Create Date: 2025-05-17 21:03:33.356662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8c09233930'
down_revision: Union[str, None] = '9cd99830e250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_belbin_answers', sa.Column('answer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_belbin_answers', 'belbin_answers', ['answer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_belbin_answers', type_='foreignkey')
    op.drop_column('user_belbin_answers', 'answer_id')
    # ### end Alembic commands ###
