"""Delete constrain in Posititon title

Revision ID: 5609ab73fbdb
Revises: 30f18779a783
Create Date: 2025-05-06 13:47:45.754473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5609ab73fbdb'
down_revision: Union[str, None] = '30f18779a783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_title', table_name='positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_positions_title', 'positions', ['title'], unique=True)
    # ### end Alembic commands ###
