"""Add has_time_limit in TestSettings

Revision ID: 5662f7ddfec5
Revises: 0f19cd31e7d0
Create Date: 2025-05-23 23:19:30.199504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5662f7ddfec5'
down_revision: Union[str, None] = '0f19cd31e7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.add_column('test_settings', sa.Column('has_time_limit', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_settings', 'has_time_limit')
 
    # ### end Alembic commands ###
