"""Add some constrains for tests

Revision ID: 5ebb2f74d2c6
Revises: f742a419f703
Create Date: 2025-05-08 22:12:08.272924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebb2f74d2c6'
down_revision: Union[str, None] = 'f742a419f703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('belbin_questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('belbin_questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('belbin_questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('belbin_questions', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
