"""Add cascades to some tables

Revision ID: 6f0b954fa7e3
Revises: 06196fd8dcdc
Create Date: 2025-05-26 21:25:30.677451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0b954fa7e3'
down_revision: Union[str, None] = '06196fd8dcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_test_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('test_results_test_id_fkey', 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tests_test_settings_id_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'test_settings', ['test_settings_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_test_settings_id_fkey', 'tests', 'test_settings', ['test_settings_id'], ['id'])
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key('test_results_test_id_fkey', 'test_results', 'tests', ['test_id'], ['id'])
  
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_test_id_fkey', 'questions', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_id_fkey', 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
