"""add points field to questions

Revision ID: 75f1fabd0e85
Revises: 78c50517ef24
Create Date: 2025-05-20 13:21:37.139611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f1fabd0e85'
down_revision: Union[str, None] = '78c50517ef24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("points", sa.Integer(), nullable=False, server_default="1"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('questions', 'points')
    # ### end Alembic commands ###
