"""Add cascade delete for employee

Revision ID: 80229d100461
Revises: 14f8daaaa2c1
Create Date: 2025-05-21 23:20:18.338423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80229d100461'
down_revision: Union[str, None] = '14f8daaaa2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('belbin_roles_created_by_id_fkey', 'belbin_roles', type_='foreignkey')
    op.create_foreign_key(None, 'belbin_roles', 'employees', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('positions_created_by_id_fkey', 'positions', type_='foreignkey')
    op.create_foreign_key(None, 'positions', 'employees', ['created_by_id'], ['id'], ondelete='CASCADE')
 
    op.drop_constraint('test_results_employee_id_fkey', 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tests_created_by_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'employees', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('user_answers', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('user_answers_employee_id_fkey', 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_belbin_answers_employee_id_fkey', 'user_belbin_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_belbin_answers', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_belbin_answers', type_='foreignkey')
    op.create_foreign_key('user_belbin_answers_employee_id_fkey', 'user_belbin_answers', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key('user_answers_employee_id_fkey', 'user_answers', 'employees', ['employee_id'], ['id'])
    op.alter_column('user_answers', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_created_by_fkey', 'tests', 'employees', ['created_by'], ['id'])
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key('test_results_employee_id_fkey', 'test_results', 'employees', ['employee_id'], ['id'])

    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.create_foreign_key('positions_created_by_id_fkey', 'positions', 'employees', ['created_by_id'], ['id'])
    op.drop_constraint(None, 'belbin_roles', type_='foreignkey')
    op.create_foreign_key('belbin_roles_created_by_id_fkey', 'belbin_roles', 'employees', ['created_by_id'], ['id'])
    # ### end Alembic commands ###
