"""Fix employee created_by field

Revision ID: 8bdaed351a2b
Revises: 933b1a979bc9
Create Date: 2025-05-13 19:07:21.112175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdaed351a2b'
down_revision: Union[str, None] = '933b1a979bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.drop_index('ix_positions_created_by', table_name='positions')
    op.create_foreign_key(None, 'positions', 'employees', ['created_by_id'], ['id'])
    op.drop_column('positions', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.create_index('ix_positions_created_by', 'positions', ['created_by'], unique=False)
    op.drop_column('positions', 'created_by_id')
    # ### end Alembic commands ###
