"""add time_limit_minutes to tests

Revision ID: b83403dac9e3
Revises: 75f1fabd0e85
Create Date: 2025-05-20 13:25:55.500112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83403dac9e3'
down_revision: Union[str, None] = '75f1fabd0e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('tests', sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'time_limit_minutes')

    # ### end Alembic commands ###
