"""Added an order for questions

Revision ID: baae11aaae99
Revises: 066b927e02b5
Create Date: 2025-05-08 20:22:44.773768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baae11aaae99'
down_revision: Union[str, None] = '066b927e02b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('belbin_questions', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'order')
    op.drop_column('belbin_questions', 'order')
    # ### end Alembic commands ###
