"""Add test_settings table

Revision ID: cc4482f4c0ad
Revises: 5ebb2f74d2c6
Create Date: 2025-05-09 18:55:18.502000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4482f4c0ad'
down_revision: Union[str, None] = '5ebb2f74d2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_questions', sa.Integer(), nullable=False),
    sa.Column('belbin_block', sa.Integer(), nullable=False),
    sa.Column('belbin_questions_in_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_settings_id'), 'test_settings', ['id'], unique=False)
    op.add_column('tests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tests', sa.Column('status', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('test_settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tests', 'test_settings', ['test_settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'test_settings_id')
    op.drop_column('tests', 'status')
    op.drop_column('tests', 'updated_at')
    op.drop_index(op.f('ix_test_settings_id'), table_name='test_settings')
    op.drop_table('test_settings')
    # ### end Alembic commands ###
