"""Add end_time in test

Revision ID: d51ffa1cc693
Revises: 46757ee53cd6
Create Date: 2025-05-09 19:58:54.814376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51ffa1cc693'
down_revision: Union[str, None] = '46757ee53cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('tests', 'time_limit_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('time_limit_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tests', 'end_date')
    # ### end Alembic commands ###
